import { Inter } from "next/font/google";
import "@/styles/globals.css"; 
import { poppins } from "@/styles/font";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${inter.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
